version: '3.2'

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - cucumber-sandbox-network 

  mitm:
    build:
      context: ./mitm
      dockerfile: Dockerfile
    networks:
      cucumber-sandbox-network:
        aliases:
          - google.com
          - www.google.com

networks:
  cucumber-sandbox-network:

