version: '3.2'

services:

  cucumber:
    build:
      context: ./cucumber
      dockerfile: Dockerfile.dev
    volumes:
      - ./cucumber:/app
    networks:
      - cucumber-sandbox-network
    command: "tail -f /dev/null"
    ports:
      - 8080:8080

  chrome:
    build:
      context: ./chrome
      dockerfile: Dockerfile
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
    ports:
      - "15900:5900"
    networks:
      - cucumber-sandbox-network 

  selenium-hub:
    image: selenium/hub:3.11.0-californium
    ports:
      - "14444:4444"
    networks:
      - cucumber-sandbox-network

  mitm:
    build:
      context: ./mitm
      dockerfile: Dockerfile
    networks:
      cucumber-sandbox-network:
        aliases:
          - google.com
          - www.google.com

networks:
  cucumber-sandbox-network:

